[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[context.production]
 
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "production", GATSBY_HEARTWOOD_LINK = "https://app.treetoplearning.org" }

[context.branch-deploy]
  
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "develop", GATSBY_HEARTWOOD_LINK = "https://develop.app.treetoplearning.org" }

[context.deploy-preview]
  
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "preview", GATSBY_HEARTWOOD_LINK = "https://develop.app.treetoplearning.org" }

[dev]
  command = "gatsby develop"
  environment = { GATSBY_HEARTWOOD_LINK = "https://develop.app.treetoplearning.org" }
